version: "2.4"

services:
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ./default.nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - colink-network
    ports:
      - "80:80"

  backend:
    container_name: backend
    environment:
      - VIRTUAL_HOST=localhost
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    networks:
      - colink-network

networks:
  colink-network:
    driver: bridge
